#!/sbin/sh
set -e

ZIP=$3
OUTFD=/proc/self/fd/$2
ui_print() { echo -e "ui_print $1\nui_print" > $OUTFD; }

if [ -d /tmp/MiuiTN ]; then rm -r /tmp/MiuiTN; fi
mkdir -p /tmp/MiuiTN/bin
unzip "$ZIP" META-INF/bin/* -d /tmp/MiuiTN
mv /tmp/MiuiTN/META-INF/bin/* /tmp/MiuiTN/bin
unzip "$ZIP" META-INF/Structure -d /tmp/MiuiTN
chmod -R 0777 /tmp/MiuiTN
structure=$(cat '/tmp/MiuiTN/META-INF/Structure')

partitionPath="/dev/block/by-name"
export PATH=/tmp/MiuiTN/bin:$PATH

ui_print "**********************************************"
ui_print ""
ui_print "      Welcome to HyperTN|MiuiTN - Mod"
ui_print "            Based on China ROM               "
ui_print "             Link: miuitn.online              "
ui_print ""
ui_print "**********************************************"
ui_print ""

if [ "$(getprop ro.product.device)" != 'rosemary' ] && [ "$(getprop ro.build.product)" != 'rosemary' ]; then 
    ui_print "Device codename does not match, your device is: $(getprop ro.product.device), check rom file"
    exit 1
fi

ui_print ">>> Installing ROM, please wait……"

for zstFile in $(7zz l "$ZIP" | grep -o "[a-z]*.new.dat.zst"); do
    partition=${zstFile%%.*}
    ui_print "> Flashing ${partition}"
    7zz x -so "$ZIP" "${zstFile}" | zstd -c -d > "${partitionPath}/${partition}"
done

for imageFile in $(7zz l "$ZIP" | grep firmware-update | grep -o "/.*" ); do
    partition=${imageFile##*/}
    partition=${partition%%.*}
    ui_print "> Flashing ${partition}"

    if [ "$partition" == "preloader_raw" ]; then
        for partitionItem in $(ls $partitionPath | grep $partition); do
            unzip -p "$ZIP" "firmware-update${imageFile}" > "${partitionPath}/${partitionItem}"
        done
    elif [ "$partition" == "boot" ] && [ "$structure" == "VAB" ]; then
        unzip -p "$ZIP" "firmware-update${imageFile}" > "${partitionPath}/${partition}_a"
        unzip -p "$ZIP" "firmware-update${imageFile}" > "${partitionPath}/${partition}_b"
    else
        unzip -p "$ZIP" "firmware-update${imageFile}" > "${partitionPath}/${partition}"
    fi
done

rm -rf /data/dalvik-cache/arm/*
rm -rf /data/dalvik-cache/arm64/*

ui_print ">>> Success"
ui_print ">>> Please ignore mount error if any"
ui_print ">>> Try format data if not boot"

exit 0
